CREATE DATABASE DUCNV_SMART

-- /CATEGORY
GO
CREATE TABLE CATEGORIES(
    [ID] BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [NAME] NVARCHAR(255) NOT NULL,
    [IMAGE] NVARCHAR(255) NOT NULL,
    [ACTIVE] BIT NOT NULL,
    [PARENT_ID] INT NOT NULL
)

--END CATEGORY \

-- /BRAND
GO
CREATE TABLE BRANDS(
    [ID] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [NAME] NVARCHAR(255) NOT NULL,
    [IMAGE] NVARCHAR(255) NOT NULL,
    [ACTIVE] BIT NOT NULL,
)
--END BRAN \

-- /PRODUCT
GO
CREATE TABLE PRODUCTS(
    [ID] BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [CODE_PRODUCT] VARCHAR(20) NOT NULL,
    [IMAGE] NVARCHAR(255) NOT NULL,
    [NAME] NVARCHAR(255) NOT NULL,
    [PRICE] FLOAT NOT NULL,
    [SALEPRICE] FLOAT NULL,
    [QUANTITY] INT NOT NULL,
    [VIEW] FLOAT NOT NULL,
    [DESCRIPTION] NVARCHAR(MAX) NULL,
    [ISNEW] BIT NOT NULL,
    [ISHOT] BIT NOT NULL,
    [ISACTIVE] BIT NOT NULL,
    [CATEGORY_ID] BIGINT NOT NULL,
    [BRAND_ID] INT NOT NULL
)


GO
CREATE TABLE PRODUCT_SALES(
    [ID] BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [SALEVALUE] FLOAT NOT NULL,
    [STARTDATE] DATETIME NULL,
    [ENDDATE] DATETIME NULL,
    [PRODUCT_ID] BIGINT NOT NULL,
)

GO
CREATE TABLE PRODUCT_VARIANTS(
    [ID] BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [NAME] NVARCHAR(255) NOT NULL,
    [IMAGE] NVARCHAR(255) NOT NULL,
    [PRICE] FLOAT NOT NULL,
    [PRICEMARKET] FLOAT NOT NULL,
    [PRICEAFTERSALE] FLOAT NOT NULL,
    [QUANTITY] INT NOT NULL,
    [ISACTIVE] BIT NOT NULL,
    [PRODUCT_ID] BIGINT NOT NULL 
)
GO
CREATE TABLE PRODUCT_IMAGES(
    [ID] BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [URL] NVARCHAR(255) NOT NULL,
    [PRODUCT_ID] BIGINT NOT NULL
)

GO
CREATE TABLE PRODUCT_ABOUTS(
    [ID] BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [CONTENT] NVARCHAR(MAX) NOT NULL,
    [PRODUCT_ID] BIGINT NOT NULL
)

GO
CREATE TABLE PRODUCT_REVIEWS(
    [ID] BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [CONTENT] NVARCHAR(MAX) NULL,
    [RATING] INT NOT NULL,
    [PRODUCT_ID] BIGINT NOT NULL
)

GO
-- Attribute
CREATE TABLE ATR_DETAIL(
    [ID] BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [NAME] NVARCHAR(255) NOT NULL,
    [ATR_VALUE] FLOAT NOT NULL,
    [PRODUCT_ID] BIGINT NOT NULL
)
-- End attribute

--END PRODUCT \

-- /Orders

CREATE TABLE PAY(
    [ID] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [TYPE] NVARCHAR(255) NOT NULL,
)

CREATE TABLE TRANSPORT_TYPE(
     [ID] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
     [TYPE] NVARCHAR(255) NOT NULL,
)

CREATE TABLE ORDER_STATUS(
    [ID] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [STATUSES] NVARCHAR(255) NOT NULL,
)

CREATE TABLE ORDERS(
    [ID] BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [PAYMENT_TYPE] INT NOT NULL,
    [TRANSPORT_TYPE] INT NOT NULL,
    [ADDRESS] NVARCHAR(255) NOT NULL,
    [PHONE] INT NOT NULL,
    [TOTAL] FLOAT NOT NULL,
    [NOTE] NVARCHAR(MAX) NULL,
    [STARTDATE] DATETIME NOT NULL,
    [STATUS] INT NOT NULL,
    [PRODUCT_ID] BIGINT NOT NULL
    -- [CUSTOMER_ID] INT NOT NULL
)

CREATE TABLE ORDER_DETAIL(
    [ID] BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [NAME] NVARCHAR(255) NOT NULL,
    [QUANTITY] INT NOT NULL,
    [ORDER_ID] BIGINT NOT NULL,
    [PRODUCT_ID] BIGINT NOT NULL
)


-- End orders \

-- /User
CREATE TABLE CUSTOMERS(
    [ID] BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [USERNAME] VARCHAR(50) NOT NULL,
    [PASSWORD] VARCHAR(255) NOT NULL,
    [GENDER] INT NOT NULL,
    [EMAIL] VARCHAR(255) NOT NULL,
    [PHONE] INT NOT NULL,
    [ADDRESS1] NVARCHAR(255) NOT NULL,
    [BIRTHDAY] DATE NULL,
    [AVATAR] NVARCHAR(255) NULL,
    [ADDRESS2] NVARCHAR(255) NULL,
    [STATUS] INT NOT NULL
)
-- End user \

-- /Display
CREATE TABLE DISPLAY(
    [ID] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [COMPANYNAME] NVARCHAR(255) NOT NULL,
    [FAVICON] NVARCHAR(255) NOT NULL,
    [HOTLINE] NVARCHAR(255) NOT NULL,
    [EMAIL] NVARCHAR(255) NOT NULL,
    [COPYRIGHT] NVARCHAR(255) NOT NULL,
    [FACEBOOK] NVARCHAR(255) NOT NULL,
    [GOOGLE] NVARCHAR(255) NOT NULL,
    [INSTAGRAM] NVARCHAR(255) NOT NULL,
    [MAP] NVARCHAR(255) NOT NULL,
)

CREATE TABLE ORTHER_DISPLAY(
    [ID] INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [DISPLAYNAME] NVARCHAR(255) NOT NULL,
    [IMAGE] NVARCHAR(255) NOT NULL,
    [ACTIVE] BIT NOT NULL
)

ALTER TABLE PRODUCTS
ADD FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID);

ALTER TABLE PRODUCTS
ADD FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(ID);

ALTER TABLE ATR_DETAIL
ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID);

ALTER TABLE PRODUCT_SALES
ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID);

ALTER TABLE PRODUCT_VARIANTS
ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID);

ALTER TABLE PRODUCT_ABOUTS
ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID);

ALTER TABLE PRODUCT_IMAGES
ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID);

ALTER TABLE PRODUCT_REVIEWS
ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID);

-- ALTER TABLE PRODUCT_IMAGES
-- ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID);




